# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  run-executor:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
#    parameters:
#     workdir:
#        type: string
#    working_directory: << parameters.workdir >>

jobs:
  build:
    executor:
      name: run-executor
#      workdir: ~/repo

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  test:
    executor:
      name: run-executor
 #     workdir: /tmp
    working_directory: /tmp
    steps:
      # run tests!
      - run: mvn integration-test
  test2:
    executor:
      name: run-executor
    working_directory: /tmp
#      workdir: /tmp
    steps:
      # run tests!
      - run: mvn integration-test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - test2:
          requires:
            - build

