# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  run-executor:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    parameters:
      workdir:
        type: string
    working_directory: << parameters.workdir >>


jobs:
  build:
    executor:
      name: run-executor
      workdir: ~/repo

#    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  test:
    executor:
      name: run-executor
      workdir: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      # run tests!
      - run: ls ~
      - run: ls ~/repo
      - run : mvn test
      - store_artifacts:
            path:  target
  test2:
    executor:
      name: run-executor
      workdir: ~/repo
    steps:
      # run tests!
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: mvn integration-test
  test3:
    executor:
      name: run-executor
      workdir: ~/repo
    steps:
      - run: mvn integration-test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: master
      - test2:
          requires:
            - build
          filters:
            branches:
              ignore: master
  build_and_test2:
    jobs:
      - test3:
          pre-steps:
            - restore_cache:
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          filters:
              branches:
                only: master

