# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  gck-management: rsmolgovsky-circleci/lengdage-gke@dev:1

workflows:
  version: 2.1
  deploy-service:
    jobs:
      - gck-management/publish-and-update-image:
          cluster: deployment-cluster-dev
          tag: latest-dev





