# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  main-executor:
    docker:
      # specify the version you desire here
      - image: maven:3.3.9-jdk-8
    working_directory: ~/repo

    environment:
      APP_TYPE: service
      APP_NAME: avm-mock

jobs:
  build:
    executor: main-executor
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn clean test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  docker_image:
    executor: main-executor
    steps:
      - attach_workspace:
          at: .
      - run: docker build -t ${APP_TYPE}001@${APP_NAME} .



workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - docker_image:
          requires:
            - build



