apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}-lb
spec:
  type: LoadBalancer
  selector:
    app: ${IMAGE_NAME}
  ports:
    - name: http
      port: 80
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${IMAGE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${IMAGE_NAME}
    spec:
      containers:
        - name: server
          image: ${REG_URL}/${G_PROJECT_ID}/${IMAGE_NAME}:${TAG}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
